
python ../lib/train.py \
    --dataset "ms1m_convfs_and_embeds" \
    --seed 777 \
    --worker_num 2 \
    --gpu_ids "0,1,2,3,4,5,6,7" \
    --batch_size 512 \
    --output_dir "../output/scf/" \
    --saved_bkb "res100.pth" \
    --saved_fc "fc.pt" \
    --num_workers 8 \
    --epochs 30 \
    --lr 3e-5 \
    --lr_scheduler "StepLR" \
    --step_size 2 \
    --gamma 0.5 \
    --weight_decay 0 \
    --convf_dim 25088 \
    --z_dim 512 \
    --radius 64 \
    --max_grad_clip 0 \
    --max_grad_norm 0 \
    --tensorboard
